### PR TITLE
Auto Pull REMARKs via GitHub Action

### PR DESCRIPTION
**Pull request by camriddell**
- Remove Chinese-Growth.md
- Remove Aiyagari-Idiosyncratic folder (shouldn't exist in this repo)
- Remove all remaining REMARKs (to be included in a build step)
- Add GitHub action to pull REMARKs before building

### CODE REVIEW

**Comment by llorracc** [comment]
@camriddell, this PR is failing checks ...

**Comment by camriddell** [comment]
@DrDrij it seems like the build failure here may be unrelated to the changes I made? Ruby failed to install the dependencies to build the site.

**Comment by camriddell** [comment]
> @DrDrij it seems like the build failure here may be unrelated to the changes I made? Ruby failed to install the dependencies to build the site.

Saw your update on the Ruby version, just had to sync up :)

**Comment by camriddell** [comment]
Merged with @llorracc approval.

**Pull request merged**
