### PR TITLE
ENH - Feature better materials search

### PR DESCRIPTION
**Pull request by camriddell**
- Add the ability to search remarks by title
- Link REMARK tabs to the choices tag system
  - the tabs are essentially common tags that we make conveniently accessible

image

title search:
image

Clicking a tab automatically adds the appropriate tag. Clicking onto a different tag will either remove or replace the appropriate tag.

image

Tags and title search work together:
image

@DrDrij, we can discuss this when we meet. Just wanted to have the PR ready.

### CODE REVIEW

**Comment by llorracc** [comment]
@camriddell, great!  If easy, it would be good to search in both "title" and other info fields in the markdown; we have not been very consistent in our naming: Some of the "title" fields seem just to contain the name of the repo.

**Comment by camriddell** [comment]
The text in the search input will now be matched against the title, each author, and the abstract and filter down to the rows that match on **any** of those fields.

image

image

@llorracc looking better?

**Comment by llorracc** [comment]
Great, thanks, big improvement!

**Comment by DrDrij** [comment]
Great work @camriddell! Speak to you tomorrow.

**Pull request merged**
