### PR TITLE
Materials filter update

### PR DESCRIPTION
**Pull request by DrDrij**
This PR adds the following functionality to the materials page:
1) Search now works across material authors
2) Clicking an author's name will list all materials from that author
3) Clicking on a material's tag (eg. DemARK) will list all materials with that tag
4) Small UX tweaks for easier search and filter

### CODE REVIEW

**Comment by camriddell** [comment]
@DrDrij know when you expect this to land?

**Comment by DrDrij** [comment]
@camriddell Thanks for the reminder. This has been ready to go for a while. I will do some final tests and get it out today.

**Comment by DrDrij** [comment]
Merging with master branch. This PR addresses intended changes:

https://econ-ark.org/materials/

- Search now works across material authors
- Clicking an author's name will list all materials from that author
- Clicking on a material's tag (eg. DemARK) will list all materials with that tag
- Small UX tweaks for easier search and filter

This allows for quicker and more specific searching such as in the following screenshot.

image

**Comment by DrDrij** [comment]
@camriddell Thanks for your additions. Let me know if I can help anywhere, I'll keep an eye out on this thread.

**Pull request merged**
